version: "3.7"
services:
  mongo:   
    image: "mongo"
    restart: always
    volumes:
      - ./data/mongodata:/var/lib/mongo
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: mongod --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${mongoRootUserName}
      - MONGO_INITDB_ROOT_PASSWORD=${mongoRootPassword}
      - MONGO_INITDB_DATABASE=${mongoDataBase}
    ports:
      - "27017:27017"
  app:
    build:
      context: ./
      # select docker base (localhost, development, production) - default localhost
      target: ${NODE_ENV:-localhost}
    environment:
      mongoHost: mongo
      mongoPort: 27017
      mongoUserName: ${mongoUserName}
      mongoDataBase: ${mongoDataBase}
      mongoPassword: ${mongoPassword}
      # select app envierment (localhost, development, production) - default localhost
      NODE_ENV: ${NODE_ENV:-localhost}
    ports: 
      - "3005:3005"
    volumes:
      - .:/app
    command: npm run dockerStart
    depends_on:
      - mongo